/**********************************************************
 * C-based/Cached/Core Computer Vision Library
 * Liu Liu, 2010-02-01
 **********************************************************/

/**********************************************************
 * CCV - Neural Network Collection
 **********************************************************/

/* This file documented all functions that doesn't exist but should be generated by Doxygen. */

#ifndef GUARD_ccv_nnc_doxygen_h
#define GUARD_ccv_nnc_doxygen_h

/**
 * @ingroup level_4
 * Create a new tensor variable without specified dimensions. Most likely this will be
 * used as output, therefore, its shape can be derived.
 * @param graph The dynamic graph.
 * @return A newly created tensor variable reference.
 */
CCV_WARN_UNUSED(ccv_nnc_tensor_variable_t) ccv_nnc_tensor_variable_new(ccv_nnc_dynamic_graph_t* const graph);
/**
 * @ingroup level_4
 * Create a new tensor variable with tensor parameters.
 * @param graph The dynamic graph.
 * @param info Tensor parameters.
 * @return A newly created tensor variable reference.
 */
CCV_WARN_UNUSED(ccv_nnc_tensor_variable_t) ccv_nnc_tensor_variable_new(ccv_nnc_dynamic_graph_t* const graph, const ccv_nnc_tensor_param_t info);

#endif
