# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Gui/ccv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Gui/ccv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Gui/ccv/CMakeFiles /Users/Gui/ccv/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Gui/ccv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ccv

# Build rule for target.
ccv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ccv
.PHONY : ccv

# fast build rule for target.
ccv/fast:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/build
.PHONY : ccv/fast

lib/3rdparty/dsfmt/dSFMT.o: lib/3rdparty/dsfmt/dSFMT.c.o
.PHONY : lib/3rdparty/dsfmt/dSFMT.o

# target to build an object file
lib/3rdparty/dsfmt/dSFMT.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/dsfmt/dSFMT.c.o
.PHONY : lib/3rdparty/dsfmt/dSFMT.c.o

lib/3rdparty/dsfmt/dSFMT.i: lib/3rdparty/dsfmt/dSFMT.c.i
.PHONY : lib/3rdparty/dsfmt/dSFMT.i

# target to preprocess a source file
lib/3rdparty/dsfmt/dSFMT.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/dsfmt/dSFMT.c.i
.PHONY : lib/3rdparty/dsfmt/dSFMT.c.i

lib/3rdparty/dsfmt/dSFMT.s: lib/3rdparty/dsfmt/dSFMT.c.s
.PHONY : lib/3rdparty/dsfmt/dSFMT.s

# target to generate assembly for a file
lib/3rdparty/dsfmt/dSFMT.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/dsfmt/dSFMT.c.s
.PHONY : lib/3rdparty/dsfmt/dSFMT.c.s

lib/3rdparty/kissfft/kiss_fft.o: lib/3rdparty/kissfft/kiss_fft.c.o
.PHONY : lib/3rdparty/kissfft/kiss_fft.o

# target to build an object file
lib/3rdparty/kissfft/kiss_fft.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kiss_fft.c.o
.PHONY : lib/3rdparty/kissfft/kiss_fft.c.o

lib/3rdparty/kissfft/kiss_fft.i: lib/3rdparty/kissfft/kiss_fft.c.i
.PHONY : lib/3rdparty/kissfft/kiss_fft.i

# target to preprocess a source file
lib/3rdparty/kissfft/kiss_fft.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kiss_fft.c.i
.PHONY : lib/3rdparty/kissfft/kiss_fft.c.i

lib/3rdparty/kissfft/kiss_fft.s: lib/3rdparty/kissfft/kiss_fft.c.s
.PHONY : lib/3rdparty/kissfft/kiss_fft.s

# target to generate assembly for a file
lib/3rdparty/kissfft/kiss_fft.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kiss_fft.c.s
.PHONY : lib/3rdparty/kissfft/kiss_fft.c.s

lib/3rdparty/kissfft/kiss_fftnd.o: lib/3rdparty/kissfft/kiss_fftnd.c.o
.PHONY : lib/3rdparty/kissfft/kiss_fftnd.o

# target to build an object file
lib/3rdparty/kissfft/kiss_fftnd.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kiss_fftnd.c.o
.PHONY : lib/3rdparty/kissfft/kiss_fftnd.c.o

lib/3rdparty/kissfft/kiss_fftnd.i: lib/3rdparty/kissfft/kiss_fftnd.c.i
.PHONY : lib/3rdparty/kissfft/kiss_fftnd.i

# target to preprocess a source file
lib/3rdparty/kissfft/kiss_fftnd.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kiss_fftnd.c.i
.PHONY : lib/3rdparty/kissfft/kiss_fftnd.c.i

lib/3rdparty/kissfft/kiss_fftnd.s: lib/3rdparty/kissfft/kiss_fftnd.c.s
.PHONY : lib/3rdparty/kissfft/kiss_fftnd.s

# target to generate assembly for a file
lib/3rdparty/kissfft/kiss_fftnd.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kiss_fftnd.c.s
.PHONY : lib/3rdparty/kissfft/kiss_fftnd.c.s

lib/3rdparty/kissfft/kiss_fftndr.o: lib/3rdparty/kissfft/kiss_fftndr.c.o
.PHONY : lib/3rdparty/kissfft/kiss_fftndr.o

# target to build an object file
lib/3rdparty/kissfft/kiss_fftndr.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kiss_fftndr.c.o
.PHONY : lib/3rdparty/kissfft/kiss_fftndr.c.o

lib/3rdparty/kissfft/kiss_fftndr.i: lib/3rdparty/kissfft/kiss_fftndr.c.i
.PHONY : lib/3rdparty/kissfft/kiss_fftndr.i

# target to preprocess a source file
lib/3rdparty/kissfft/kiss_fftndr.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kiss_fftndr.c.i
.PHONY : lib/3rdparty/kissfft/kiss_fftndr.c.i

lib/3rdparty/kissfft/kiss_fftndr.s: lib/3rdparty/kissfft/kiss_fftndr.c.s
.PHONY : lib/3rdparty/kissfft/kiss_fftndr.s

# target to generate assembly for a file
lib/3rdparty/kissfft/kiss_fftndr.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kiss_fftndr.c.s
.PHONY : lib/3rdparty/kissfft/kiss_fftndr.c.s

lib/3rdparty/kissfft/kiss_fftr.o: lib/3rdparty/kissfft/kiss_fftr.c.o
.PHONY : lib/3rdparty/kissfft/kiss_fftr.o

# target to build an object file
lib/3rdparty/kissfft/kiss_fftr.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kiss_fftr.c.o
.PHONY : lib/3rdparty/kissfft/kiss_fftr.c.o

lib/3rdparty/kissfft/kiss_fftr.i: lib/3rdparty/kissfft/kiss_fftr.c.i
.PHONY : lib/3rdparty/kissfft/kiss_fftr.i

# target to preprocess a source file
lib/3rdparty/kissfft/kiss_fftr.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kiss_fftr.c.i
.PHONY : lib/3rdparty/kissfft/kiss_fftr.c.i

lib/3rdparty/kissfft/kiss_fftr.s: lib/3rdparty/kissfft/kiss_fftr.c.s
.PHONY : lib/3rdparty/kissfft/kiss_fftr.s

# target to generate assembly for a file
lib/3rdparty/kissfft/kiss_fftr.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kiss_fftr.c.s
.PHONY : lib/3rdparty/kissfft/kiss_fftr.c.s

lib/3rdparty/kissfft/kissf_fft.o: lib/3rdparty/kissfft/kissf_fft.c.o
.PHONY : lib/3rdparty/kissfft/kissf_fft.o

# target to build an object file
lib/3rdparty/kissfft/kissf_fft.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kissf_fft.c.o
.PHONY : lib/3rdparty/kissfft/kissf_fft.c.o

lib/3rdparty/kissfft/kissf_fft.i: lib/3rdparty/kissfft/kissf_fft.c.i
.PHONY : lib/3rdparty/kissfft/kissf_fft.i

# target to preprocess a source file
lib/3rdparty/kissfft/kissf_fft.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kissf_fft.c.i
.PHONY : lib/3rdparty/kissfft/kissf_fft.c.i

lib/3rdparty/kissfft/kissf_fft.s: lib/3rdparty/kissfft/kissf_fft.c.s
.PHONY : lib/3rdparty/kissfft/kissf_fft.s

# target to generate assembly for a file
lib/3rdparty/kissfft/kissf_fft.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kissf_fft.c.s
.PHONY : lib/3rdparty/kissfft/kissf_fft.c.s

lib/3rdparty/kissfft/kissf_fftnd.o: lib/3rdparty/kissfft/kissf_fftnd.c.o
.PHONY : lib/3rdparty/kissfft/kissf_fftnd.o

# target to build an object file
lib/3rdparty/kissfft/kissf_fftnd.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kissf_fftnd.c.o
.PHONY : lib/3rdparty/kissfft/kissf_fftnd.c.o

lib/3rdparty/kissfft/kissf_fftnd.i: lib/3rdparty/kissfft/kissf_fftnd.c.i
.PHONY : lib/3rdparty/kissfft/kissf_fftnd.i

# target to preprocess a source file
lib/3rdparty/kissfft/kissf_fftnd.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kissf_fftnd.c.i
.PHONY : lib/3rdparty/kissfft/kissf_fftnd.c.i

lib/3rdparty/kissfft/kissf_fftnd.s: lib/3rdparty/kissfft/kissf_fftnd.c.s
.PHONY : lib/3rdparty/kissfft/kissf_fftnd.s

# target to generate assembly for a file
lib/3rdparty/kissfft/kissf_fftnd.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kissf_fftnd.c.s
.PHONY : lib/3rdparty/kissfft/kissf_fftnd.c.s

lib/3rdparty/kissfft/kissf_fftndr.o: lib/3rdparty/kissfft/kissf_fftndr.c.o
.PHONY : lib/3rdparty/kissfft/kissf_fftndr.o

# target to build an object file
lib/3rdparty/kissfft/kissf_fftndr.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kissf_fftndr.c.o
.PHONY : lib/3rdparty/kissfft/kissf_fftndr.c.o

lib/3rdparty/kissfft/kissf_fftndr.i: lib/3rdparty/kissfft/kissf_fftndr.c.i
.PHONY : lib/3rdparty/kissfft/kissf_fftndr.i

# target to preprocess a source file
lib/3rdparty/kissfft/kissf_fftndr.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kissf_fftndr.c.i
.PHONY : lib/3rdparty/kissfft/kissf_fftndr.c.i

lib/3rdparty/kissfft/kissf_fftndr.s: lib/3rdparty/kissfft/kissf_fftndr.c.s
.PHONY : lib/3rdparty/kissfft/kissf_fftndr.s

# target to generate assembly for a file
lib/3rdparty/kissfft/kissf_fftndr.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kissf_fftndr.c.s
.PHONY : lib/3rdparty/kissfft/kissf_fftndr.c.s

lib/3rdparty/kissfft/kissf_fftr.o: lib/3rdparty/kissfft/kissf_fftr.c.o
.PHONY : lib/3rdparty/kissfft/kissf_fftr.o

# target to build an object file
lib/3rdparty/kissfft/kissf_fftr.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kissf_fftr.c.o
.PHONY : lib/3rdparty/kissfft/kissf_fftr.c.o

lib/3rdparty/kissfft/kissf_fftr.i: lib/3rdparty/kissfft/kissf_fftr.c.i
.PHONY : lib/3rdparty/kissfft/kissf_fftr.i

# target to preprocess a source file
lib/3rdparty/kissfft/kissf_fftr.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kissf_fftr.c.i
.PHONY : lib/3rdparty/kissfft/kissf_fftr.c.i

lib/3rdparty/kissfft/kissf_fftr.s: lib/3rdparty/kissfft/kissf_fftr.c.s
.PHONY : lib/3rdparty/kissfft/kissf_fftr.s

# target to generate assembly for a file
lib/3rdparty/kissfft/kissf_fftr.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/kissfft/kissf_fftr.c.s
.PHONY : lib/3rdparty/kissfft/kissf_fftr.c.s

lib/3rdparty/sfmt/SFMT.o: lib/3rdparty/sfmt/SFMT.c.o
.PHONY : lib/3rdparty/sfmt/SFMT.o

# target to build an object file
lib/3rdparty/sfmt/SFMT.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/sfmt/SFMT.c.o
.PHONY : lib/3rdparty/sfmt/SFMT.c.o

lib/3rdparty/sfmt/SFMT.i: lib/3rdparty/sfmt/SFMT.c.i
.PHONY : lib/3rdparty/sfmt/SFMT.i

# target to preprocess a source file
lib/3rdparty/sfmt/SFMT.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/sfmt/SFMT.c.i
.PHONY : lib/3rdparty/sfmt/SFMT.c.i

lib/3rdparty/sfmt/SFMT.s: lib/3rdparty/sfmt/SFMT.c.s
.PHONY : lib/3rdparty/sfmt/SFMT.s

# target to generate assembly for a file
lib/3rdparty/sfmt/SFMT.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/sfmt/SFMT.c.s
.PHONY : lib/3rdparty/sfmt/SFMT.c.s

lib/3rdparty/sha1/sha1.o: lib/3rdparty/sha1/sha1.c.o
.PHONY : lib/3rdparty/sha1/sha1.o

# target to build an object file
lib/3rdparty/sha1/sha1.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/sha1/sha1.c.o
.PHONY : lib/3rdparty/sha1/sha1.c.o

lib/3rdparty/sha1/sha1.i: lib/3rdparty/sha1/sha1.c.i
.PHONY : lib/3rdparty/sha1/sha1.i

# target to preprocess a source file
lib/3rdparty/sha1/sha1.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/sha1/sha1.c.i
.PHONY : lib/3rdparty/sha1/sha1.c.i

lib/3rdparty/sha1/sha1.s: lib/3rdparty/sha1/sha1.c.s
.PHONY : lib/3rdparty/sha1/sha1.s

# target to generate assembly for a file
lib/3rdparty/sha1/sha1.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/sha1/sha1.c.s
.PHONY : lib/3rdparty/sha1/sha1.c.s

lib/3rdparty/sqlite3/sqlite3.o: lib/3rdparty/sqlite3/sqlite3.c.o
.PHONY : lib/3rdparty/sqlite3/sqlite3.o

# target to build an object file
lib/3rdparty/sqlite3/sqlite3.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/sqlite3/sqlite3.c.o
.PHONY : lib/3rdparty/sqlite3/sqlite3.c.o

lib/3rdparty/sqlite3/sqlite3.i: lib/3rdparty/sqlite3/sqlite3.c.i
.PHONY : lib/3rdparty/sqlite3/sqlite3.i

# target to preprocess a source file
lib/3rdparty/sqlite3/sqlite3.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/sqlite3/sqlite3.c.i
.PHONY : lib/3rdparty/sqlite3/sqlite3.c.i

lib/3rdparty/sqlite3/sqlite3.s: lib/3rdparty/sqlite3/sqlite3.c.s
.PHONY : lib/3rdparty/sqlite3/sqlite3.s

# target to generate assembly for a file
lib/3rdparty/sqlite3/sqlite3.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/3rdparty/sqlite3/sqlite3.c.s
.PHONY : lib/3rdparty/sqlite3/sqlite3.c.s

lib/ccv_algebra.o: lib/ccv_algebra.c.o
.PHONY : lib/ccv_algebra.o

# target to build an object file
lib/ccv_algebra.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_algebra.c.o
.PHONY : lib/ccv_algebra.c.o

lib/ccv_algebra.i: lib/ccv_algebra.c.i
.PHONY : lib/ccv_algebra.i

# target to preprocess a source file
lib/ccv_algebra.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_algebra.c.i
.PHONY : lib/ccv_algebra.c.i

lib/ccv_algebra.s: lib/ccv_algebra.c.s
.PHONY : lib/ccv_algebra.s

# target to generate assembly for a file
lib/ccv_algebra.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_algebra.c.s
.PHONY : lib/ccv_algebra.c.s

lib/ccv_basic.o: lib/ccv_basic.c.o
.PHONY : lib/ccv_basic.o

# target to build an object file
lib/ccv_basic.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_basic.c.o
.PHONY : lib/ccv_basic.c.o

lib/ccv_basic.i: lib/ccv_basic.c.i
.PHONY : lib/ccv_basic.i

# target to preprocess a source file
lib/ccv_basic.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_basic.c.i
.PHONY : lib/ccv_basic.c.i

lib/ccv_basic.s: lib/ccv_basic.c.s
.PHONY : lib/ccv_basic.s

# target to generate assembly for a file
lib/ccv_basic.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_basic.c.s
.PHONY : lib/ccv_basic.c.s

lib/ccv_bbf.o: lib/ccv_bbf.c.o
.PHONY : lib/ccv_bbf.o

# target to build an object file
lib/ccv_bbf.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_bbf.c.o
.PHONY : lib/ccv_bbf.c.o

lib/ccv_bbf.i: lib/ccv_bbf.c.i
.PHONY : lib/ccv_bbf.i

# target to preprocess a source file
lib/ccv_bbf.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_bbf.c.i
.PHONY : lib/ccv_bbf.c.i

lib/ccv_bbf.s: lib/ccv_bbf.c.s
.PHONY : lib/ccv_bbf.s

# target to generate assembly for a file
lib/ccv_bbf.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_bbf.c.s
.PHONY : lib/ccv_bbf.c.s

lib/ccv_cache.o: lib/ccv_cache.c.o
.PHONY : lib/ccv_cache.o

# target to build an object file
lib/ccv_cache.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_cache.c.o
.PHONY : lib/ccv_cache.c.o

lib/ccv_cache.i: lib/ccv_cache.c.i
.PHONY : lib/ccv_cache.i

# target to preprocess a source file
lib/ccv_cache.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_cache.c.i
.PHONY : lib/ccv_cache.c.i

lib/ccv_cache.s: lib/ccv_cache.c.s
.PHONY : lib/ccv_cache.s

# target to generate assembly for a file
lib/ccv_cache.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_cache.c.s
.PHONY : lib/ccv_cache.c.s

lib/ccv_classic.o: lib/ccv_classic.c.o
.PHONY : lib/ccv_classic.o

# target to build an object file
lib/ccv_classic.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_classic.c.o
.PHONY : lib/ccv_classic.c.o

lib/ccv_classic.i: lib/ccv_classic.c.i
.PHONY : lib/ccv_classic.i

# target to preprocess a source file
lib/ccv_classic.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_classic.c.i
.PHONY : lib/ccv_classic.c.i

lib/ccv_classic.s: lib/ccv_classic.c.s
.PHONY : lib/ccv_classic.s

# target to generate assembly for a file
lib/ccv_classic.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_classic.c.s
.PHONY : lib/ccv_classic.c.s

lib/ccv_convnet.o: lib/ccv_convnet.c.o
.PHONY : lib/ccv_convnet.o

# target to build an object file
lib/ccv_convnet.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_convnet.c.o
.PHONY : lib/ccv_convnet.c.o

lib/ccv_convnet.i: lib/ccv_convnet.c.i
.PHONY : lib/ccv_convnet.i

# target to preprocess a source file
lib/ccv_convnet.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_convnet.c.i
.PHONY : lib/ccv_convnet.c.i

lib/ccv_convnet.s: lib/ccv_convnet.c.s
.PHONY : lib/ccv_convnet.s

# target to generate assembly for a file
lib/ccv_convnet.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_convnet.c.s
.PHONY : lib/ccv_convnet.c.s

lib/ccv_daisy.o: lib/ccv_daisy.c.o
.PHONY : lib/ccv_daisy.o

# target to build an object file
lib/ccv_daisy.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_daisy.c.o
.PHONY : lib/ccv_daisy.c.o

lib/ccv_daisy.i: lib/ccv_daisy.c.i
.PHONY : lib/ccv_daisy.i

# target to preprocess a source file
lib/ccv_daisy.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_daisy.c.i
.PHONY : lib/ccv_daisy.c.i

lib/ccv_daisy.s: lib/ccv_daisy.c.s
.PHONY : lib/ccv_daisy.s

# target to generate assembly for a file
lib/ccv_daisy.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_daisy.c.s
.PHONY : lib/ccv_daisy.c.s

lib/ccv_dpm.o: lib/ccv_dpm.c.o
.PHONY : lib/ccv_dpm.o

# target to build an object file
lib/ccv_dpm.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_dpm.c.o
.PHONY : lib/ccv_dpm.c.o

lib/ccv_dpm.i: lib/ccv_dpm.c.i
.PHONY : lib/ccv_dpm.i

# target to preprocess a source file
lib/ccv_dpm.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_dpm.c.i
.PHONY : lib/ccv_dpm.c.i

lib/ccv_dpm.s: lib/ccv_dpm.c.s
.PHONY : lib/ccv_dpm.s

# target to generate assembly for a file
lib/ccv_dpm.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_dpm.c.s
.PHONY : lib/ccv_dpm.c.s

lib/ccv_ferns.o: lib/ccv_ferns.c.o
.PHONY : lib/ccv_ferns.o

# target to build an object file
lib/ccv_ferns.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_ferns.c.o
.PHONY : lib/ccv_ferns.c.o

lib/ccv_ferns.i: lib/ccv_ferns.c.i
.PHONY : lib/ccv_ferns.i

# target to preprocess a source file
lib/ccv_ferns.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_ferns.c.i
.PHONY : lib/ccv_ferns.c.i

lib/ccv_ferns.s: lib/ccv_ferns.c.s
.PHONY : lib/ccv_ferns.s

# target to generate assembly for a file
lib/ccv_ferns.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_ferns.c.s
.PHONY : lib/ccv_ferns.c.s

lib/ccv_icf.o: lib/ccv_icf.c.o
.PHONY : lib/ccv_icf.o

# target to build an object file
lib/ccv_icf.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_icf.c.o
.PHONY : lib/ccv_icf.c.o

lib/ccv_icf.i: lib/ccv_icf.c.i
.PHONY : lib/ccv_icf.i

# target to preprocess a source file
lib/ccv_icf.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_icf.c.i
.PHONY : lib/ccv_icf.c.i

lib/ccv_icf.s: lib/ccv_icf.c.s
.PHONY : lib/ccv_icf.s

# target to generate assembly for a file
lib/ccv_icf.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_icf.c.s
.PHONY : lib/ccv_icf.c.s

lib/ccv_io.o: lib/ccv_io.c.o
.PHONY : lib/ccv_io.o

# target to build an object file
lib/ccv_io.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_io.c.o
.PHONY : lib/ccv_io.c.o

lib/ccv_io.i: lib/ccv_io.c.i
.PHONY : lib/ccv_io.i

# target to preprocess a source file
lib/ccv_io.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_io.c.i
.PHONY : lib/ccv_io.c.i

lib/ccv_io.s: lib/ccv_io.c.s
.PHONY : lib/ccv_io.s

# target to generate assembly for a file
lib/ccv_io.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_io.c.s
.PHONY : lib/ccv_io.c.s

lib/ccv_memory.o: lib/ccv_memory.c.o
.PHONY : lib/ccv_memory.o

# target to build an object file
lib/ccv_memory.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_memory.c.o
.PHONY : lib/ccv_memory.c.o

lib/ccv_memory.i: lib/ccv_memory.c.i
.PHONY : lib/ccv_memory.i

# target to preprocess a source file
lib/ccv_memory.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_memory.c.i
.PHONY : lib/ccv_memory.c.i

lib/ccv_memory.s: lib/ccv_memory.c.s
.PHONY : lib/ccv_memory.s

# target to generate assembly for a file
lib/ccv_memory.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_memory.c.s
.PHONY : lib/ccv_memory.c.s

lib/ccv_mser.o: lib/ccv_mser.c.o
.PHONY : lib/ccv_mser.o

# target to build an object file
lib/ccv_mser.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_mser.c.o
.PHONY : lib/ccv_mser.c.o

lib/ccv_mser.i: lib/ccv_mser.c.i
.PHONY : lib/ccv_mser.i

# target to preprocess a source file
lib/ccv_mser.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_mser.c.i
.PHONY : lib/ccv_mser.c.i

lib/ccv_mser.s: lib/ccv_mser.c.s
.PHONY : lib/ccv_mser.s

# target to generate assembly for a file
lib/ccv_mser.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_mser.c.s
.PHONY : lib/ccv_mser.c.s

lib/ccv_numeric.o: lib/ccv_numeric.c.o
.PHONY : lib/ccv_numeric.o

# target to build an object file
lib/ccv_numeric.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_numeric.c.o
.PHONY : lib/ccv_numeric.c.o

lib/ccv_numeric.i: lib/ccv_numeric.c.i
.PHONY : lib/ccv_numeric.i

# target to preprocess a source file
lib/ccv_numeric.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_numeric.c.i
.PHONY : lib/ccv_numeric.c.i

lib/ccv_numeric.s: lib/ccv_numeric.c.s
.PHONY : lib/ccv_numeric.s

# target to generate assembly for a file
lib/ccv_numeric.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_numeric.c.s
.PHONY : lib/ccv_numeric.c.s

lib/ccv_resample.o: lib/ccv_resample.c.o
.PHONY : lib/ccv_resample.o

# target to build an object file
lib/ccv_resample.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_resample.c.o
.PHONY : lib/ccv_resample.c.o

lib/ccv_resample.i: lib/ccv_resample.c.i
.PHONY : lib/ccv_resample.i

# target to preprocess a source file
lib/ccv_resample.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_resample.c.i
.PHONY : lib/ccv_resample.c.i

lib/ccv_resample.s: lib/ccv_resample.c.s
.PHONY : lib/ccv_resample.s

# target to generate assembly for a file
lib/ccv_resample.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_resample.c.s
.PHONY : lib/ccv_resample.c.s

lib/ccv_sift.o: lib/ccv_sift.c.o
.PHONY : lib/ccv_sift.o

# target to build an object file
lib/ccv_sift.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_sift.c.o
.PHONY : lib/ccv_sift.c.o

lib/ccv_sift.i: lib/ccv_sift.c.i
.PHONY : lib/ccv_sift.i

# target to preprocess a source file
lib/ccv_sift.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_sift.c.i
.PHONY : lib/ccv_sift.c.i

lib/ccv_sift.s: lib/ccv_sift.c.s
.PHONY : lib/ccv_sift.s

# target to generate assembly for a file
lib/ccv_sift.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_sift.c.s
.PHONY : lib/ccv_sift.c.s

lib/ccv_sparse_coding.o: lib/ccv_sparse_coding.c.o
.PHONY : lib/ccv_sparse_coding.o

# target to build an object file
lib/ccv_sparse_coding.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_sparse_coding.c.o
.PHONY : lib/ccv_sparse_coding.c.o

lib/ccv_sparse_coding.i: lib/ccv_sparse_coding.c.i
.PHONY : lib/ccv_sparse_coding.i

# target to preprocess a source file
lib/ccv_sparse_coding.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_sparse_coding.c.i
.PHONY : lib/ccv_sparse_coding.c.i

lib/ccv_sparse_coding.s: lib/ccv_sparse_coding.c.s
.PHONY : lib/ccv_sparse_coding.s

# target to generate assembly for a file
lib/ccv_sparse_coding.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_sparse_coding.c.s
.PHONY : lib/ccv_sparse_coding.c.s

lib/ccv_swt.o: lib/ccv_swt.c.o
.PHONY : lib/ccv_swt.o

# target to build an object file
lib/ccv_swt.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_swt.c.o
.PHONY : lib/ccv_swt.c.o

lib/ccv_swt.i: lib/ccv_swt.c.i
.PHONY : lib/ccv_swt.i

# target to preprocess a source file
lib/ccv_swt.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_swt.c.i
.PHONY : lib/ccv_swt.c.i

lib/ccv_swt.s: lib/ccv_swt.c.s
.PHONY : lib/ccv_swt.s

# target to generate assembly for a file
lib/ccv_swt.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_swt.c.s
.PHONY : lib/ccv_swt.c.s

lib/ccv_tld.o: lib/ccv_tld.c.o
.PHONY : lib/ccv_tld.o

# target to build an object file
lib/ccv_tld.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_tld.c.o
.PHONY : lib/ccv_tld.c.o

lib/ccv_tld.i: lib/ccv_tld.c.i
.PHONY : lib/ccv_tld.i

# target to preprocess a source file
lib/ccv_tld.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_tld.c.i
.PHONY : lib/ccv_tld.c.i

lib/ccv_tld.s: lib/ccv_tld.c.s
.PHONY : lib/ccv_tld.s

# target to generate assembly for a file
lib/ccv_tld.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_tld.c.s
.PHONY : lib/ccv_tld.c.s

lib/ccv_transform.o: lib/ccv_transform.c.o
.PHONY : lib/ccv_transform.o

# target to build an object file
lib/ccv_transform.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_transform.c.o
.PHONY : lib/ccv_transform.c.o

lib/ccv_transform.i: lib/ccv_transform.c.i
.PHONY : lib/ccv_transform.i

# target to preprocess a source file
lib/ccv_transform.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_transform.c.i
.PHONY : lib/ccv_transform.c.i

lib/ccv_transform.s: lib/ccv_transform.c.s
.PHONY : lib/ccv_transform.s

# target to generate assembly for a file
lib/ccv_transform.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_transform.c.s
.PHONY : lib/ccv_transform.c.s

lib/ccv_util.o: lib/ccv_util.c.o
.PHONY : lib/ccv_util.o

# target to build an object file
lib/ccv_util.c.o:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_util.c.o
.PHONY : lib/ccv_util.c.o

lib/ccv_util.i: lib/ccv_util.c.i
.PHONY : lib/ccv_util.i

# target to preprocess a source file
lib/ccv_util.c.i:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_util.c.i
.PHONY : lib/ccv_util.c.i

lib/ccv_util.s: lib/ccv_util.c.s
.PHONY : lib/ccv_util.s

# target to generate assembly for a file
lib/ccv_util.c.s:
	$(MAKE) -f CMakeFiles/ccv.dir/build.make CMakeFiles/ccv.dir/lib/ccv_util.c.s
.PHONY : lib/ccv_util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ccv"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... lib/3rdparty/dsfmt/dSFMT.o"
	@echo "... lib/3rdparty/dsfmt/dSFMT.i"
	@echo "... lib/3rdparty/dsfmt/dSFMT.s"
	@echo "... lib/3rdparty/kissfft/kiss_fft.o"
	@echo "... lib/3rdparty/kissfft/kiss_fft.i"
	@echo "... lib/3rdparty/kissfft/kiss_fft.s"
	@echo "... lib/3rdparty/kissfft/kiss_fftnd.o"
	@echo "... lib/3rdparty/kissfft/kiss_fftnd.i"
	@echo "... lib/3rdparty/kissfft/kiss_fftnd.s"
	@echo "... lib/3rdparty/kissfft/kiss_fftndr.o"
	@echo "... lib/3rdparty/kissfft/kiss_fftndr.i"
	@echo "... lib/3rdparty/kissfft/kiss_fftndr.s"
	@echo "... lib/3rdparty/kissfft/kiss_fftr.o"
	@echo "... lib/3rdparty/kissfft/kiss_fftr.i"
	@echo "... lib/3rdparty/kissfft/kiss_fftr.s"
	@echo "... lib/3rdparty/kissfft/kissf_fft.o"
	@echo "... lib/3rdparty/kissfft/kissf_fft.i"
	@echo "... lib/3rdparty/kissfft/kissf_fft.s"
	@echo "... lib/3rdparty/kissfft/kissf_fftnd.o"
	@echo "... lib/3rdparty/kissfft/kissf_fftnd.i"
	@echo "... lib/3rdparty/kissfft/kissf_fftnd.s"
	@echo "... lib/3rdparty/kissfft/kissf_fftndr.o"
	@echo "... lib/3rdparty/kissfft/kissf_fftndr.i"
	@echo "... lib/3rdparty/kissfft/kissf_fftndr.s"
	@echo "... lib/3rdparty/kissfft/kissf_fftr.o"
	@echo "... lib/3rdparty/kissfft/kissf_fftr.i"
	@echo "... lib/3rdparty/kissfft/kissf_fftr.s"
	@echo "... lib/3rdparty/sfmt/SFMT.o"
	@echo "... lib/3rdparty/sfmt/SFMT.i"
	@echo "... lib/3rdparty/sfmt/SFMT.s"
	@echo "... lib/3rdparty/sha1/sha1.o"
	@echo "... lib/3rdparty/sha1/sha1.i"
	@echo "... lib/3rdparty/sha1/sha1.s"
	@echo "... lib/3rdparty/sqlite3/sqlite3.o"
	@echo "... lib/3rdparty/sqlite3/sqlite3.i"
	@echo "... lib/3rdparty/sqlite3/sqlite3.s"
	@echo "... lib/ccv_algebra.o"
	@echo "... lib/ccv_algebra.i"
	@echo "... lib/ccv_algebra.s"
	@echo "... lib/ccv_basic.o"
	@echo "... lib/ccv_basic.i"
	@echo "... lib/ccv_basic.s"
	@echo "... lib/ccv_bbf.o"
	@echo "... lib/ccv_bbf.i"
	@echo "... lib/ccv_bbf.s"
	@echo "... lib/ccv_cache.o"
	@echo "... lib/ccv_cache.i"
	@echo "... lib/ccv_cache.s"
	@echo "... lib/ccv_classic.o"
	@echo "... lib/ccv_classic.i"
	@echo "... lib/ccv_classic.s"
	@echo "... lib/ccv_convnet.o"
	@echo "... lib/ccv_convnet.i"
	@echo "... lib/ccv_convnet.s"
	@echo "... lib/ccv_daisy.o"
	@echo "... lib/ccv_daisy.i"
	@echo "... lib/ccv_daisy.s"
	@echo "... lib/ccv_dpm.o"
	@echo "... lib/ccv_dpm.i"
	@echo "... lib/ccv_dpm.s"
	@echo "... lib/ccv_ferns.o"
	@echo "... lib/ccv_ferns.i"
	@echo "... lib/ccv_ferns.s"
	@echo "... lib/ccv_icf.o"
	@echo "... lib/ccv_icf.i"
	@echo "... lib/ccv_icf.s"
	@echo "... lib/ccv_io.o"
	@echo "... lib/ccv_io.i"
	@echo "... lib/ccv_io.s"
	@echo "... lib/ccv_memory.o"
	@echo "... lib/ccv_memory.i"
	@echo "... lib/ccv_memory.s"
	@echo "... lib/ccv_mser.o"
	@echo "... lib/ccv_mser.i"
	@echo "... lib/ccv_mser.s"
	@echo "... lib/ccv_numeric.o"
	@echo "... lib/ccv_numeric.i"
	@echo "... lib/ccv_numeric.s"
	@echo "... lib/ccv_resample.o"
	@echo "... lib/ccv_resample.i"
	@echo "... lib/ccv_resample.s"
	@echo "... lib/ccv_sift.o"
	@echo "... lib/ccv_sift.i"
	@echo "... lib/ccv_sift.s"
	@echo "... lib/ccv_sparse_coding.o"
	@echo "... lib/ccv_sparse_coding.i"
	@echo "... lib/ccv_sparse_coding.s"
	@echo "... lib/ccv_swt.o"
	@echo "... lib/ccv_swt.i"
	@echo "... lib/ccv_swt.s"
	@echo "... lib/ccv_tld.o"
	@echo "... lib/ccv_tld.i"
	@echo "... lib/ccv_tld.s"
	@echo "... lib/ccv_transform.o"
	@echo "... lib/ccv_transform.i"
	@echo "... lib/ccv_transform.s"
	@echo "... lib/ccv_util.o"
	@echo "... lib/ccv_util.i"
	@echo "... lib/ccv_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

