/**********************************************************
 * C-based/Cached/Core Computer Vision Library
 * Liu Liu, 2010-02-01
 **********************************************************/

/* This file documented all functions that doesn't exist but should be generated by Doxygen. */

#ifndef GUARD_ccv_doxygen_h
#define GUARD_ccv_doxygen_h

int ccv_read(const char* in, ccv_dense_matrix_t** x, int type);
int ccv_read(const void* data, ccv_dense_matrix_t** x, int type, int size);
int ccv_read(const void* data, ccv_dense_matrix_t** x, int type, int rows, int cols, int scanline);

#endif
